theme: jekyll-theme-hacker
title: Fission21
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 无聊的时候写点诗

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  null # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
